EAD_project/Models/loginForm.cs
using System;
using System.Linq;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations; //Model Validation


namespace EAD_project.Models
{
    public class loginForm
    {
        [Required(ErrorMessage = "please enter your name")]

        public string email { get; set; }



        [StringLength(15)]
        [Required(ErrorMessage = "please enter password")]

        public string password { get; set; }
        
    }
}

EAD_project/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using EAD_project.Models;
using EAD_project.Models.Interface;
using Newtonsoft.Json;

namespace EAD_project.Controllers

{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly ICustomer customer;

        public LoginController(ILogger<LoginController> logger, ICustomer c)
        {
            _logger = logger;
            customer = c;
        }
        [HttpGet]

        public IActionResult signin()
        {
            if (!HttpContext.Request.Cookies.ContainsKey("loginUser"))
            { return View(); 
            }
            return RedirectToAction("homepage", "Home");
        }



        [HttpPost]
        public IActionResult signin(loginForm loginForm)
        {
            if (customer.matchData(loginForm.email,loginForm.password) != null)
            {
                string user = JsonConvert.SerializeObject(customer.matchData(loginForm.email, loginForm.password));
                HttpContext.Response.Cookies.Append("LoginUser", user,
                    new Microsoft.AspNetCore.Http.CookieOptions
                    {
                        Expires = DateTimeOffset.UtcNow.AddYears(1)
                    });
                return RedirectToAction("homepage", "Home");
            }
            return View();

            /*if (customer.matchData(loginForm.email, loginForm.password))
            {
                return RedirectToAction("homepage", "Home");
            }
            else
            {
                return signin();
            }*/



        }
    }
}

EAD_project/Controllers/SignupController.cs
using Microsoft.AspNetCore.Mvc;
using EAD_project.Models;
using System.Diagnostics;
using EAD_project.Models.Interface;

namespace EAD_project.Controllers
{
    public class SignupController : Controller
    {
        private readonly ILogger<SignupController> _logger;
        private readonly IWebHostEnvironment Environment;
        private readonly ICustomer customer;

        public SignupController(ILogger<SignupController> logger, IWebHostEnvironment environment, ICustomer c)
        {
            _logger = logger;
            Environment = environment;
            customer = c;
        }

        [HttpGet]
        public ViewResult registerForm()
        {
            return View();
        }
        //string name, string email, string password, string cnic, string phoneNumber
        [HttpPost]
        public IActionResult registerForm(CDatum l, List<IFormFile> postedFiles)
        {
            string wwwPath = this.Environment.WebRootPath;
            string path = Path.Combine(wwwPath, "Uploads");
            Console.WriteLine("pathh",path);
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            foreach (var file in postedFiles)
            {
                var fileName = Path.GetFileName(file.FileName);
                var pathWithFileName = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(pathWithFileName, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
            }
            customer.saveData(l);
            return RedirectToAction("signin", "Login");
        }
        
    }
}










/*  if (ModelState.IsValid)
              {
                  //DBClass.saveData(l);

                  return View("Thanks");

              }
              else
              {
                  ModelState.AddModelError(String.Empty, "Please enter correct data");//generic msg show 
                  return View();
              }*/

EAD_project/Views/Login/signin.cshtml
@using EAD_project.Models;
@model loginForm
<!DOCTYPE html>
<html lang="en">
<head>
 <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
<style>
    body {
  margin: 0;
  padding: 0;
  background-color: #17a2b8;
  height: 100vh;
}
#login .container #login-row #login-column #login-box {
  margin-top: 120px;
  max-width: 600px;
  height: 320px;
  border: 1px solid #9C9C9C;
  background-color: #EAEAEA;
}
#login .container #login-row #login-column #login-box #login-form {
  padding: 20px;
}
#login .container #login-row #login-column #login-box #login-form #register-link {
  margin-top: -85px;
}
</style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a href="/admin/adminView"><button class="btn btn-outline-success my-2 my-sm-0" type="submit">Click to Login as Admin</button>
  </div>
</nav>

         <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                        <form action="/Login/signin" style="" class="login-form" id="UserLoginForm" method="post" accept-charset="utf-8">
                                    
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input asp-for="email" id="login-username" type="text" class="form-control" placeholder=" enter email" required="required" maxlength="255" value="" >                                        
                                    </div>
                                
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input asp-for="password" id="login-password" type="password" class="form-control" placeholder=" enter password" required="required"
                                        >
                                    </div>
                                    

                                
                            <div class="input-group">
                                      <div class="checkbox">
                                        <label>
                                          <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                                        </label>
                                      </div>
                                    </div>


                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <button type ="submit" class="btn btn-success">Login  </button>
                                      <a id="btn-fblogin" href="#" class="btn btn-primary">Login with Facebook</a>

                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Don't have an account! 
                                        <a href="@Url.Action("registerForm", "Signup")"> Click here </a>
                                        </div>
                                    </div>
                                </div>    
                            </form>     



                        </div>                     
              </div>  
        </div>
    </div>
</body>
</html>